config/routes.rb
Rails.application.routes.draw do
  resources :sp_carts
  resources :carts

    root "products#index"
    

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :carts
end

app/models/sp_cart.rb
class SpCart < ApplicationRecord
    has_many :product

    def sub_total
        sum = 0
        self.order_details.each do |order_detail|
        sum+= order_detail.total_price
        end
        return sum
      end
    
      def sum_quan
        sum = 0
        self.order_details.each do |order_detail|
          sum += order_detail.quantity
        end
        sum
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

    def index
        @products = Product.all
    end
end

app/controllers/sp_carts_controller.rb
class SpCartsController < ApplicationController
  before_action :set_sp_cart, only: %i[ show edit update destroy ]

  # GET /sp_carts or /sp_carts.json
  def index
    @sp_carts = SpCart.all
  end

  # GET /sp_carts/1 or /sp_carts/1.json
  def show
  end

  # GET /sp_carts/new
  def new
    @sp_cart = SpCart.new
  end

  # GET /sp_carts/1/edit
  def edit
  end

  # POST /sp_carts or /sp_carts.json
  def create
    @sp_cart = SpCart.new(sp_cart_params)

    respond_to do |format|
      if @sp_cart.save
        format.html { redirect_to sp_cart_url(@sp_cart), notice: "Sp cart was successfully created." }
        format.json { render :show, status: :created, location: @sp_cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sp_cart.errors, status: :unprocessable_entity }
      end
    end
  end
  #
  def create
    chosen_product = Product.find(params[:product_id])
    if sp_cart.product.include?(chosen_product)
        @sp_cart = sp_cart.order_details.find_by(:product_id => chosen_product)
        @sp_cart.quantity += 1
    else
        @sp_cart = sp_cart.new 
        @sp_cart.cart = current_cart
        @sp_cart.product = chosen_product
        @sp_cart.quantity = 1
    end     
    @order_detail.price = @order_detail.quantity * @order_detail.product.price
    @order_detail.order_id = Order.maximum(:id).next
    @order_detail.save 
end
  # PATCH/PUT /sp_carts/1 or /sp_carts/1.json
  def update
    respond_to do |format|
      if @sp_cart.update(sp_cart_params)
        format.html { redirect_to sp_cart_url(@sp_cart), notice: "Sp cart was successfully updated." }
        format.json { render :show, status: :ok, location: @sp_cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sp_cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sp_carts/1 or /sp_carts/1.json
  def destroy
    @sp_cart.destroy

    respond_to do |format|
      format.html { redirect_to sp_carts_url, notice: "Sp cart was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sp_cart
      @sp_cart = SpCart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sp_cart_params
      params.require(:sp_cart).permit(:id_product, :quantity)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/sp_carts_helper.rb
module SpCartsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/show_pro.html.erb
<div class="container py-2">
  <%= link_to 'Back', products_path, :class => 'btn btn-danger mb-2' %>
  <p id="notice" class='text-success'><%= notice %></p>
  <div class="card">
    <h5 class="card-header"><%= @product.name %>
    </h5>
    <div class="card-body">
      <div class='row align-items-start'>
          <div class='col'>
          <p class="lead">
            <strong>Name</strong>
            <%= @product.name %>
          </p>

           <p class="lead">
            <strong>description</strong>
            <%= @product.des %>
          </p>

          <p class="lead"> 
            <strong>Price:</strong>
            <%= @product.price %>
          </p>

          <p class="lead">
            <strong>Color</strong>
            <%= @product.color %>
          </p>
          <p class="lead">
            <strong>Image:</strong>
              <div class='image-product'>
                <%= image_tag(@product.image, style: 'width:100%')%>
              </div>
          </p> 
          </div>
          <div class='col'>
            <div class='card w-50 float-end'>
            <h4 class="card-header">Add properties</h4>
              <div class='card-body'>
                <%= render 'properties/form' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/sp_carts/_form.html.erb
<%= form_with(model: sp_cart) do |form| %>
  <% if sp_cart.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(sp_cart.errors.count, "error") %> prohibited this sp_cart from being saved:</h2>

      <ul>
        <% sp_cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :id_product, style: "display: block" %>
    <%= form.number_field :id_product %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/sp_carts/_sp_cart.html.erb
<div id="<%= dom_id sp_cart %>">
  <p>
    <strong>Id product:</strong>
    <%= sp_cart.id_product %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= sp_cart.quantity %>
  </p>

</div>

app/views/sp_carts/edit.html.erb
<h1>Editing sp cart</h1>

<%= render "form", sp_cart: @sp_cart %>

<br>

<div>
  <%= link_to "Show this sp cart", @sp_cart %> |
  <%= link_to "Back to sp carts", sp_carts_path %>
</div>

app/views/sp_carts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Sp carts</h1>

<div id="sp_carts">
  <% @sp_carts.each do |sp_cart| %>
    <%= render sp_cart %>
    <p>
      <%= link_to "Show this sp cart", sp_cart %>
    </p>
  <% end %>
</div>

<%= link_to "New sp cart", new_sp_cart_path %>

app/views/sp_carts/new.html.erb
<h1>New sp cart</h1>

<%= render "form", sp_cart: @sp_cart %>

<br>

<div>
  <%= link_to "Back to sp carts", sp_carts_path %>
</div>

app/views/sp_carts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @sp_cart %>

<div>
  <%= link_to "Edit this sp cart", edit_sp_cart_path(@sp_cart) %> |
  <%= link_to "Back to sp carts", sp_carts_path %>

  <%= button_to "Destroy this sp cart", @sp_cart, method: :delete %>
</div>